### ISSUE TITLE
Cant download pkg

### ISSUE THREAD

**Issue by spusuf** [tschettervictor/truenas-iocage-uptimekuma#1]
The installation fails because the jail cant reach the servers to get pkg. This has happened on multiple occasions even when not using scripted iocage installs, and the only solution seems to be enable to DHCP and set a static IP in the router. 

Is there a way to use DHCP in the script (or fix the underlying truenas issue)

**Comment by tschettervictor** [comment]
It would be possible to run this with DHCP. You would need to remove all JAIL_IP variable lines in the script and edit the jail creation command to set DHCP to “on”

Your issue sounds like you might not have set the gateway IP in the config file, or your network settings in TrueNAS itself might not be properly configured.

I would suggest starting a thread explaining this.

**Comment by spusuf** [comment]
The error becomes "JAIL_IP must be set" 
Also tried with jail ip set and it goes back to setting a vnet and fails.

**Comment by tschettervictor** [comment]
Try commenting out lines 54-57

**Comment by spusuf** [comment]
The error becomes "DEFAULT_GATEWAY must be set"  and if thats commented out then you get a "Please provide a valid ip: Address cannot be empty" so I'm usure how to force DHCP during jail creation

**Comment by tschettervictor** [comment]
You could try to just create a jail, then run the commands starting from after the jail creation command.

This script was not designed for DHCP though. I would suggest figuring out why it is you need to set the jail to DHCP for it to work.
